apiVersion: apps/v1
kind: Deployment
metadata: 
  name: url-shortener-backend
  namespace: {{ .Values.namespace }}
  labels: 
    app: url-shortener-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-shortener-backend
  template:
    metadata:
      labels:
        app: url-shortener-backend
    spec:
      containers:
        - name: url-shortener-backend
          image: docker.io/library/url-shortener-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: APP_SOCKET
              value: {{ .Values.appSocket }}
            - name: REDIS_SOCKET
              value: {{ .Values.redisSocket }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /encode/https%3A%2F%2Fwww.rust-lang.org%2F
              port: 8080
            periodSeconds: 3
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 10
            periodSeconds: 3