apiVersion: apps/v1
kind: Deployment
metadata: 
  name: url-shortener-backend
  namespace: {{ .Values.namespace }}
  labels: 
    app: url-shortener-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-shortener-backend
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 120
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: url-shortener-backend
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
      containers:
        - name: url-shortener-backend
          image: danieldidiobalsamo/url-shortener-backend:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "5m"
              memory: "5Mi"
            limits:
              cpu: "20m"
              memory: "16Mi"
          volumeMounts:
            - name: redis-passwd
              readOnly: true
              mountPath: "/etc/redis-passwd"
          env:
            - name: REDIS_RO_ENDPOINT
              value: {{ .Values.redisROEndpoint }}
            - name: REDIS_RW_ENDPOINT
              value: {{ .Values.redisRWEndpoint }}
            - name: APP_SOCKET
              value: {{ .Values.appSocket }}
          securityContext:
            runAsUser: 2000
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /encode/https%3A%2F%2Fwww.rust-lang.org%2F
              port: 8080
            periodSeconds: 3
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 10
            periodSeconds: 3
      volumes:
      - name: redis-passwd
        secret:
          secretName: redis-passwd