pipeline{
	agent any

	stages{
		stage('kubeconform'){
			agent {
	            docker { image 'golang:latest' }
	        }
			steps{
				// install helm
				sh 'curl https://get.helm.sh/helm-v3.12.0-linux-amd64.tar.gz --output ./helm.tar.gz'
				sh 'tar -zxvf helm.tar.gz'

				sh 'GOCACHE=$WORKSPACE go install github.com/yannh/kubeconform/cmd/kubeconform@latest'
				sh 'linux-amd64/helm template deployment/url-shortener/charts/url-shortener-frontend | kubeconform --verbose'
			}
		}
	}
}