apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sts
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "redis-write"
  selector:
    matchLabels:
      app: redis-sts
  replicas: 6
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: redis-sts
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
      containers:
      - name: redis
        image: redis:7.0
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: data
          mountPath: /data
          readOnly: false
        - name: config
          readOnly: true
          mountPath: /mnt
        - name: redis-passwd
          readOnly: true
          mountPath: "/etc/redis-passwd"
        securityContext:
          runAsUser: 2000
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        command:
          - bash
          - -c
          - /mnt/launch.sh
      volumes:
      - name: config
        configMap:
          name: redis-config
          defaultMode: 0777
      - name: redis-passwd
        secret:
          secretName: redis-passwd
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi