apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: {{ .Values.namespace }}
  labels:
    app: redis
data:

  launch.sh: |

    if [[ $HOSTNAME == "redis-sts-0" ]]; then
      redis-server /mnt/master.conf
    else
      redis-server --replicaof redis-sts-0.redis-write.url-shortener-redis.svc.cluster.local 6379
    fi

  master.conf: |
    dir /data
    cluster-config-file /data/nodes.conf
    protected-mode no