# read only redis
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  sessionAffinity: None
  type: ClusterIP

---
# read/write redis,  headless service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-write
  name: redis-write
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  ports:
  - port: 6379
  selector:
    app: redis-sts