apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: url-shortener-frontend
  namespace: {{ .Values.namespace }}
  name: url-shortener-frontend
spec:
  rules:
  - host: {{ .Values.applicationDomainName }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: url-shortener-frontend
            port: 
              number: 80