apiVersion: v1
kind: Service
metadata:
  name: url-shortener-frontend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: url-shortener-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80