[package]
name = "url_shortener_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
ammonia = "4.0.0"
url = "2.5.4"
actix-cors = "0.7.0"

url_shortener_algo = {path = "../url_shortener_algo"}
url_shortener_redis = {path = "../url_shortener_redis"}