[package]
name = "url_shortener_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
ammonia = "3.2.1"
url = "2.3.1"
actix-cors = "0.6.1"

url_shortener_algo = {path = "../url_shortener_algo"}
url_shortener_redis = {path = "../url_shortener_redis"}