apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: url-shortener-redis
  labels:
    app: redis
data:
  redis.conf: |
    cluster-enabled yes
    bind 0.0.0.0
    port 6379

    dir /data
    dbfilename dump.rdb
    appendonly yes
    appendfilename "appendonly.aof"
    cluster-config-file /data/nodes.conf 
    protected-mode no
