apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sts
  namespace: url-shortener-redis
spec:
  serviceName: "redis-write"
  selector:
    matchLabels:
      app: redis-sts
  replicas: 6
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: redis-sts
    spec:
      containers:
      - name: redis
        image: redis:7.0
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /mnt
        command:
          - bash
          - -c
          - redis-server /mnt/redis.conf
      volumes:
      - name: config
        configMap:
          name: redis-config
          defaultMode: 0777
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi