apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-sts
  name: redis-write
  namespace: url-shortener-redis
spec:
  clusterIP: None
  ports:
  - port: 6379
  selector:
    app: redis-sts
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-sts
  name: redis-read
  namespace: url-shortener-redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-sts
  sessionAffinity: None
  type: ClusterIP