apiVersion: apps/v1
kind: Deployment
metadata: 
  name: url-shortener-deployment
  namespace: {{ .Values.namespace }}
  labels: 
    app: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener
          image: docker.io/library/url-shortener:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_SOCKET
              value: 'redis-service:6379'
            - name: APP_SOCKET
              value: '0.0.0.0:8080'