apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: url-shortener
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080