apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: {{ .Values.namespace }}
spec:
  tls: 
  - hosts:
    - short.home
    secretName: web-ssl
  rules:
  - host: short.home
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: url-shortener-service
            port: 
              number: 8080