apiVersion: apps/v1
kind: Deployment
metadata: 
  name: url-shortener-frontend
  namespace: {{ .Values.namespace }}
  labels: 
    app: url-shortener-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener-frontend
  template:
    metadata:
      labels:
        app: url-shortener-frontend
    spec:
      automountServiceAccountToken: false
      containers:
        - name: url-shortener-frontend
          image: docker.io/library/url-shortener-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "3m"
              memory: "16Mi"
            limits:
              cpu: "10m"
              memory: "25Mi"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
              add: ["CAP_CHOWN", "CAP_SETGID", "CAP_SETUID"]